<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Beranda_fx-monitor-logotype</name>
   <tag></tag>
   <elementGuidId>bbf368a5-4cdc-4b2f-be57-8a2e6ae96344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fx-monitor-logotype</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navigation-wrapper']/section/a/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fx-monitor-logotype</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navigation-wrapper&quot;)/section[@class=&quot;row-full-width fxm-branding&quot;]/a[@class=&quot;flx-cntr fx-monitor-logo-wrapper&quot;]/div[@class=&quot;fx-monitor-logotype&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navigation-wrapper']/section/a/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]</value>
   </webElementXpaths>
</WebElementEntity>
